### ISSUE TITLE
Add docker network task

### ISSUE THREAD

**Issue by zahodi** [senorsmile/ansible-docker_deploy#6]
With docker deprecating container "links" I think it should make sense to introduce a network task to the role.

https://docs.docker.com/network/links/
https://docs.ansible.com/ansible/2.5/modules/docker_network_module.html

**Comment by senorsmile** [comment]
Great point.  PR welcomed (wink wink).

**Comment by zahodi** [comment]
https://github.com/senorsmile/ansible-docker_deploy/pull/7

**Comment by zahodi** [comment]
Resolved in https://github.com/senorsmile/ansible-docker_deploy/pull/7
